title: Dimas Trio Roysaputra # your name (or website title) here
logo: "/images/IMG_3045.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  On going education at Sumatra Institute of Technology (ITERA) and persuing Engineering Physics degree.
  <br><br>
  Have a little experience at Programming and Data Analyst, good programming skills such as Python, PHP, and JavaScript
  <br><br>
  <a href="https://www.linkedin.com/in/trioroys/">My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
